# Generated by Django 4.0.1 on 2022-01-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('coverimage', models.ImageField(upload_to='img')),
                ('movie', models.FileField(blank=True, upload_to='movie')),
            ],
        ),
    ]
